version: 2
updates:
  # Maintain Python dependencies
  - package-ecosystem: "uv"
    directories:
      - "/pythonbible"
      - "/pythonbible-akjv"
      - "/pythonbible-asv"
      - "/pythonbible-bbe"
      - "/pythonbible-bwe"
      - "/pythonbible-dar"
      - "/pythonbible-diaglot"
      - "/pythonbible-dr"
      - "/pythonbible-etheridge"
      - "/pythonbible-gb"
      - "/pythonbible-kjv"
      - "/pythonbible-leeser"
      - "/pythonbible-lont"
      - "/pythonbible-mkjv1963."
      - "/pythonbible-mont"
    schedule:
      interval: "daily"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
