# This file was automatically generated by the pythonbible-parser package on 2024-05-28 22:17:47.844901+00:00.

from pythonbible.books import Book


short_titles = {
    Book.MATTHEW: '',
    Book.MARK: '',
    Book.LUKE: '',
    Book.JOHN: '',
    Book.ACTS: '',
    Book.ROMANS: '',
    Book.CORINTHIANS_1: '',
    Book.CORINTHIANS_2: '',
    Book.GALATIANS: '',
    Book.EPHESIANS: '',
    Book.PHILIPPIANS: '',
    Book.COLOSSIANS: '',
    Book.THESSALONIANS_1: '',
    Book.THESSALONIANS_2: '',
    Book.TIMOTHY_1: '',
    Book.TIMOTHY_2: '',
    Book.TITUS: '',
    Book.PHILEMON: '',
    Book.HEBREWS: '',
    Book.JAMES: '',
    Book.PETER_1: '',
    Book.PETER_2: '',
    Book.JOHN_1: '',
    Book.JOHN_2: '',
    Book.JOHN_3: '',
    Book.JUDE: '',
    Book.REVELATION: '',
}

long_titles = {
    Book.MATTHEW: '
      ',
    Book.MARK: '
      ',
    Book.LUKE: '
      ',
    Book.JOHN: '
      ',
    Book.ACTS: '
      ',
    Book.ROMANS: '
      ',
    Book.CORINTHIANS_1: '
      ',
    Book.CORINTHIANS_2: '
      ',
    Book.GALATIANS: '
      ',
    Book.EPHESIANS: '
      ',
    Book.PHILIPPIANS: '
      ',
    Book.COLOSSIANS: '
      ',
    Book.THESSALONIANS_1: '
      ',
    Book.THESSALONIANS_2: '
      ',
    Book.TIMOTHY_1: '
      ',
    Book.TIMOTHY_2: '
      ',
    Book.TITUS: '
      ',
    Book.PHILEMON: '
      ',
    Book.HEBREWS: '
      ',
    Book.JAMES: '
      ',
    Book.PETER_1: '
      ',
    Book.PETER_2: '
      ',
    Book.JOHN_1: '
      ',
    Book.JOHN_2: '
      ',
    Book.JOHN_3: '
      ',
    Book.JUDE: '
      ',
    Book.REVELATION: '
      ',
}
