# This file was automatically generated by the pythonbible-parser package on 2024-05-31 20:23:23.910769+00:00.

from pythonbible.books import Book
from pythonbible.versions import Version

from . import html_bible
from . import html_notes_bible
from . import html_readers_bible
from . import plain_text_bible
from . import plain_text_notes_bible
from . import plain_text_readers_bible


BIBLES = {
    Version.LEESER: {
         "html": html_bible.bible,
         "html_notes": html_notes_bible.bible,
         "html_readers": html_readers_bible.bible,
         "plain_text": plain_text_bible.bible,
         "plain_text_notes": plain_text_notes_bible.bible,
         "plain_text_readers": plain_text_readers_bible.bible,
    }
}


SHORT_TITLES = {
    Book.GENESIS: "Genesis",
    Book.EXODUS: "Exodus",
    Book.LEVITICUS: "Leviticus",
    Book.NUMBERS: "Numbers",
    Book.DEUTERONOMY: "Deuteronomy",
    Book.JOSHUA: "Joshua",
    Book.JUDGES: "Judges",
    Book.RUTH: "Ruth",
    Book.SAMUEL_1: "1 Samuel",
    Book.SAMUEL_2: "2 Samuel",
    Book.KINGS_1: "1 Kings",
    Book.KINGS_2: "2 Kings",
    Book.CHRONICLES_1: "1 Chronicles",
    Book.CHRONICLES_2: "2 Chronicles",
    Book.EZRA: "Ezra",
    Book.NEHEMIAH: "Nehemiah",
    Book.ESTHER: "Esther",
    Book.JOB: "Job",
    Book.PSALMS: "Psalms",
    Book.PROVERBS: "Proverbs",
    Book.ECCLESIASTES: "Ecclesiastes",
    Book.SONG_OF_SONGS: "Song of Songs",
    Book.ISAIAH: "Isaiah",
    Book.JEREMIAH: "Jeremiah",
    Book.LAMENTATIONS: "Lamentations",
    Book.EZEKIEL: "Ezekiel",
    Book.DANIEL: "Daniel",
    Book.HOSEA: "Hosea",
    Book.JOEL: "Joel",
    Book.AMOS: "Amos",
    Book.OBADIAH: "Obadiah",
    Book.JONAH: "Jonah",
    Book.MICAH: "Micah",
    Book.NAHUM: "Nahum",
    Book.HABAKKUK: "Habakkuk",
    Book.ZEPHANIAH: "Zephaniah",
    Book.HAGGAI: "Haggai",
    Book.ZECHARIAH: "Zechariah",
    Book.MALACHI: "Malachi",
}

LONG_TITLES = {
    Book.GENESIS: "Genesis",
    Book.EXODUS: "Exodus",
    Book.LEVITICUS: "Leviticus",
    Book.NUMBERS: "Numbers",
    Book.DEUTERONOMY: "Deuteronomy",
    Book.JOSHUA: "Joshua",
    Book.JUDGES: "Judges",
    Book.RUTH: "Ruth",
    Book.SAMUEL_1: "1 Samuel",
    Book.SAMUEL_2: "2 Samuel",
    Book.KINGS_1: "1 Kings",
    Book.KINGS_2: "2 Kings",
    Book.CHRONICLES_1: "1 Chronicles",
    Book.CHRONICLES_2: "2 Chronicles",
    Book.EZRA: "Ezra",
    Book.NEHEMIAH: "Nehemiah",
    Book.ESTHER: "Esther",
    Book.JOB: "Job",
    Book.PSALMS: "Psalms",
    Book.PROVERBS: "Proverbs",
    Book.ECCLESIASTES: "Ecclesiastes",
    Book.SONG_OF_SONGS: "Song of Songs",
    Book.ISAIAH: "Isaiah",
    Book.JEREMIAH: "Jeremiah",
    Book.LAMENTATIONS: "Lamentations",
    Book.EZEKIEL: "Ezekiel",
    Book.DANIEL: "Daniel",
    Book.HOSEA: "Hosea",
    Book.JOEL: "Joel",
    Book.AMOS: "Amos",
    Book.OBADIAH: "Obadiah",
    Book.JONAH: "Jonah",
    Book.MICAH: "Micah",
    Book.NAHUM: "Nahum",
    Book.HABAKKUK: "Habakkuk",
    Book.ZEPHANIAH: "Zephaniah",
    Book.HAGGAI: "Haggai",
    Book.ZECHARIAH: "Zechariah",
    Book.MALACHI: "Malachi",
}
