# This file was automatically generated by the pythonbible-parser package on 2024-05-31 20:24:05.831494+00:00.

from pythonbible.books import Book
from pythonbible.versions import Version

from . import html_bible
from . import html_notes_bible
from . import html_readers_bible
from . import plain_text_bible
from . import plain_text_notes_bible
from . import plain_text_readers_bible


BIBLES = {
    Version.WESLEY_NT: {
         "html": html_bible.bible,
         "html_notes": html_notes_bible.bible,
         "html_readers": html_readers_bible.bible,
         "plain_text": plain_text_bible.bible,
         "plain_text_notes": plain_text_notes_bible.bible,
         "plain_text_readers": plain_text_readers_bible.bible,
    }
}


SHORT_TITLES = {
    Book.MATTHEW: "Matthew",
    Book.MARK: "Mark",
    Book.LUKE: "Luke",
    Book.JOHN: "John",
    Book.ACTS: "Acts",
    Book.ROMANS: "Romans",
    Book.CORINTHIANS_1: "1 Corinthians",
    Book.CORINTHIANS_2: "2 Corinthians",
    Book.GALATIANS: "Galatians",
    Book.EPHESIANS: "Ephesians",
    Book.PHILIPPIANS: "Philippians",
    Book.COLOSSIANS: "Colossians",
    Book.THESSALONIANS_1: "1 Thessalonians",
    Book.THESSALONIANS_2: "2 Thessalonians",
    Book.TIMOTHY_1: "1 Timothy",
    Book.TIMOTHY_2: "2 Timothy",
    Book.TITUS: "Titus",
    Book.PHILEMON: "Philemon",
    Book.HEBREWS: "Hebrews",
    Book.JAMES: "James",
    Book.PETER_1: "1 Peter",
    Book.PETER_2: "2 Peter",
    Book.JOHN_1: "1 John",
    Book.JOHN_2: "2 John",
    Book.JOHN_3: "3 John",
    Book.JUDE: "Jude",
    Book.REVELATION: "Revelation",
}

LONG_TITLES = {
    Book.MATTHEW: "Matthew",
    Book.MARK: "Mark",
    Book.LUKE: "Luke",
    Book.JOHN: "John",
    Book.ACTS: "Acts",
    Book.ROMANS: "Romans",
    Book.CORINTHIANS_1: "1 Corinthians",
    Book.CORINTHIANS_2: "2 Corinthians",
    Book.GALATIANS: "Galatians",
    Book.EPHESIANS: "Ephesians",
    Book.PHILIPPIANS: "Philippians",
    Book.COLOSSIANS: "Colossians",
    Book.THESSALONIANS_1: "1 Thessalonians",
    Book.THESSALONIANS_2: "2 Thessalonians",
    Book.TIMOTHY_1: "1 Timothy",
    Book.TIMOTHY_2: "2 Timothy",
    Book.TITUS: "Titus",
    Book.PHILEMON: "Philemon",
    Book.HEBREWS: "Hebrews",
    Book.JAMES: "James",
    Book.PETER_1: "1 Peter",
    Book.PETER_2: "2 Peter",
    Book.JOHN_1: "1 John",
    Book.JOHN_2: "2 John",
    Book.JOHN_3: "3 John",
    Book.JUDE: "Jude",
    Book.REVELATION: "Revelation",
}
