from enum import Enum, auto
from typing import Dict, List

from .books import Book


class BookGroup(Enum):
    OLD_TESTAMENT = auto()
    OLD_TESTAMENT_LAW = auto()
    OLD_TESTAMENT_HISTORY = auto()
    OLD_TESTAMENT_POETRY_WISDOM = auto()
    OLD_TESTAMENT_PROPHECY = auto()
    OLD_TESTAMENT_MAJOR_PROPHETS = auto()
    OLD_TESTAMENT_MINOR_PROPHETS = auto()
    NEW_TESTAMENT = auto()
    NEW_TESTAMENT_GOSPELS = auto()
    NEW_TESTAMENT_HISTORY = auto()
    NEW_TESTAMENT_EPISTLES = auto()
    NEW_TESTAMENT_PAUL_EPISTLES = auto()
    NEW_TESTAMENT_GENERAL_EPISTLES = auto()
    NEW_TESTAMENT_APOCALYPTIC = auto()

    @property
    def books(self) -> List[Book]:
        return _BOOK_GROUP_BOOKS.get(self, [])


OLD_TESTAMENT_LAW_BOOKS: List[Book] = [
    Book.GENESIS,
    Book.EXODUS,
    Book.LEVITICUS,
    Book.NUMBERS,
    Book.DEUTERONOMY,
]

OLD_TESTAMENT_HISTORY_BOOKS: List[Book] = [
    Book.JOSHUA,
    Book.JUDGES,
    Book.RUTH,
    Book.SAMUEL_1,
    Book.SAMUEL_2,
    Book.KINGS_1,
    Book.KINGS_2,
    Book.CHRONICLES_1,
    Book.CHRONICLES_2,
    Book.EZRA,
    Book.NEHEMIAH,
    Book.ESTHER,
]

OLD_TESTAMENT_POETRY_WISDOM_BOOKS: List[Book] = [
    Book.JOB,
    Book.PSALMS,
    Book.PROVERBS,
    Book.ECCLESIASTES,
    Book.SONG_OF_SONGS,
]

OLD_TESTAMENT_MAJOR_PROPHETS_BOOKS: List[Book] = [
    Book.ISAIAH,
    Book.JEREMIAH,
    Book.LAMENTATIONS,
    Book.EZEKIEL,
    Book.DANIEL,
]

OLD_TESTAMENT_MINOR_PROPHETS_BOOKS: List[Book] = [
    Book.HOSEA,
    Book.JOEL,
    Book.AMOS,
    Book.OBADIAH,
    Book.JONAH,
    Book.MICAH,
    Book.NAHUM,
    Book.HABAKKUK,
    Book.ZEPHANIAH,
    Book.HAGGAI,
    Book.ZECHARIAH,
    Book.MALACHI,
]

OLD_TESTAMENT_PROPHECY_BOOKS: List[Book] = (
    OLD_TESTAMENT_MAJOR_PROPHETS_BOOKS + OLD_TESTAMENT_MINOR_PROPHETS_BOOKS
)

OLD_TESTAMENT_BOOKS: List[Book] = (
    OLD_TESTAMENT_LAW_BOOKS
    + OLD_TESTAMENT_HISTORY_BOOKS
    + OLD_TESTAMENT_POETRY_WISDOM_BOOKS
    + OLD_TESTAMENT_PROPHECY_BOOKS
)

NEW_TESTAMENT_GOSPELS_BOOKS: List[Book] = [
    Book.MATTHEW,
    Book.MARK,
    Book.LUKE,
    Book.JOHN,
]

NEW_TESTAMENT_HISTORY_BOOKS: List[Book] = [
    Book.ACTS,
]

NEW_TESTAMENT_PAUL_EPISTLES_BOOKS: List[Book] = [
    Book.ROMANS,
    Book.CORINTHIANS_1,
    Book.CORINTHIANS_2,
    Book.GALATIANS,
    Book.EPHESIANS,
    Book.PHILIPPIANS,
    Book.COLOSSIANS,
    Book.THESSALONIANS_1,
    Book.THESSALONIANS_2,
    Book.TIMOTHY_1,
    Book.TIMOTHY_2,
    Book.TITUS,
    Book.PHILEMON,
]

NEW_TESTAMENT_GENERAL_EPISTLES_BOOKS: List[Book] = [
    Book.HEBREWS,
    Book.JAMES,
    Book.PETER_1,
    Book.PETER_2,
    Book.JOHN_1,
    Book.JOHN_2,
    Book.JOHN_3,
    Book.JUDE,
]

NEW_TESTAMENT_EPISTLES_BOOKS: List[Book] = (
    NEW_TESTAMENT_PAUL_EPISTLES_BOOKS + NEW_TESTAMENT_GENERAL_EPISTLES_BOOKS
)

NEW_TESTAMENT_APOCALYPTIC_BOOKS: List[Book] = [
    Book.REVELATION,
]

NEW_TESTAMENT_BOOKS: List[Book] = (
    NEW_TESTAMENT_GOSPELS_BOOKS
    + NEW_TESTAMENT_HISTORY_BOOKS
    + NEW_TESTAMENT_EPISTLES_BOOKS
    + NEW_TESTAMENT_APOCALYPTIC_BOOKS
)

_BOOK_GROUP_BOOKS: Dict[BookGroup, List[Book]] = {
    BookGroup.OLD_TESTAMENT: OLD_TESTAMENT_BOOKS,
    BookGroup.OLD_TESTAMENT_LAW: OLD_TESTAMENT_LAW_BOOKS,
    BookGroup.OLD_TESTAMENT_HISTORY: OLD_TESTAMENT_HISTORY_BOOKS,
    BookGroup.OLD_TESTAMENT_POETRY_WISDOM: OLD_TESTAMENT_POETRY_WISDOM_BOOKS,
    BookGroup.OLD_TESTAMENT_PROPHECY: OLD_TESTAMENT_PROPHECY_BOOKS,
    BookGroup.OLD_TESTAMENT_MAJOR_PROPHETS: OLD_TESTAMENT_MAJOR_PROPHETS_BOOKS,
    BookGroup.OLD_TESTAMENT_MINOR_PROPHETS: OLD_TESTAMENT_MINOR_PROPHETS_BOOKS,
    BookGroup.NEW_TESTAMENT: NEW_TESTAMENT_BOOKS,
    BookGroup.NEW_TESTAMENT_GOSPELS: NEW_TESTAMENT_GOSPELS_BOOKS,
    BookGroup.NEW_TESTAMENT_HISTORY: NEW_TESTAMENT_HISTORY_BOOKS,
    BookGroup.NEW_TESTAMENT_EPISTLES: NEW_TESTAMENT_EPISTLES_BOOKS,
    BookGroup.NEW_TESTAMENT_PAUL_EPISTLES: NEW_TESTAMENT_PAUL_EPISTLES_BOOKS,
    BookGroup.NEW_TESTAMENT_GENERAL_EPISTLES: NEW_TESTAMENT_GENERAL_EPISTLES_BOOKS,
    BookGroup.NEW_TESTAMENT_APOCALYPTIC: NEW_TESTAMENT_APOCALYPTIC_BOOKS,
}
