# This file was automatically generated by the pythonbible-parser package on 2024-05-28 22:18:02.415789+00:00.

from pythonbible.books import Book


short_titles = {
    Book.GENESIS: '',
    Book.EXODUS: '',
    Book.LEVITICUS: '',
    Book.NUMBERS: '',
    Book.DEUTERONOMY: '',
    Book.JOSHUA: '',
    Book.JUDGES: '',
    Book.RUTH: '',
    Book.SAMUEL_1: '',
    Book.SAMUEL_2: '',
    Book.KINGS_1: '',
    Book.KINGS_2: '',
    Book.CHRONICLES_1: '',
    Book.CHRONICLES_2: '',
    Book.EZRA: '',
    Book.NEHEMIAH: '',
    Book.ESTHER: '',
    Book.JOB: '',
    Book.PSALMS: '',
    Book.PROVERBS: '',
    Book.ECCLESIASTES: '',
    Book.SONG_OF_SONGS: '',
    Book.ISAIAH: '',
    Book.JEREMIAH: '',
    Book.LAMENTATIONS: '',
    Book.EZEKIEL: '',
    Book.DANIEL: '',
    Book.HOSEA: '',
    Book.JOEL: '',
    Book.AMOS: '',
    Book.OBADIAH: '',
    Book.JONAH: '',
    Book.MICAH: '',
    Book.NAHUM: '',
    Book.HABAKKUK: '',
    Book.ZEPHANIAH: '',
    Book.HAGGAI: '',
    Book.ZECHARIAH: '',
    Book.MALACHI: '',
}

long_titles = {
    Book.GENESIS: '
      ',
    Book.EXODUS: '
      ',
    Book.LEVITICUS: '
      ',
    Book.NUMBERS: '
      ',
    Book.DEUTERONOMY: '
      ',
    Book.JOSHUA: '
      ',
    Book.JUDGES: '
      ',
    Book.RUTH: '
      ',
    Book.SAMUEL_1: '
      ',
    Book.SAMUEL_2: '
      ',
    Book.KINGS_1: '
      ',
    Book.KINGS_2: '
      ',
    Book.CHRONICLES_1: '
      ',
    Book.CHRONICLES_2: '
      ',
    Book.EZRA: '
      ',
    Book.NEHEMIAH: '
      ',
    Book.ESTHER: '
      ',
    Book.JOB: '
      ',
    Book.PSALMS: '
      ',
    Book.PROVERBS: '
      ',
    Book.ECCLESIASTES: '
      ',
    Book.SONG_OF_SONGS: '
      ',
    Book.ISAIAH: '
      ',
    Book.JEREMIAH: '
      ',
    Book.LAMENTATIONS: '
      ',
    Book.EZEKIEL: '
      ',
    Book.DANIEL: '
      ',
    Book.HOSEA: '
      ',
    Book.JOEL: '
      ',
    Book.AMOS: '
      ',
    Book.OBADIAH: '
      ',
    Book.JONAH: '
      ',
    Book.MICAH: '
      ',
    Book.NAHUM: '
      ',
    Book.HABAKKUK: '
      ',
    Book.ZEPHANIAH: '
      ',
    Book.HAGGAI: '
      ',
    Book.ZECHARIAH: '
      ',
    Book.MALACHI: '
      ',
}
