#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Version {
    // Open Source or Public Domain English Translations
    AMERICAN_KING_JAMES,
    AMERICAN_STANDARD,
    BIBLE_IN_BASIC_ENGLISH,
    WORLWIDE_ENGLISH,
    DARBY,
    DIAGLOT_NT,
    DOUAY_RHEIMS,
    ROTHERHAM,
    GENEVA,
    KING_JAMES,
    LEESER,
    LIVING_ORACLES_NT,
    KING_JAMES_MODERN_1963,
    MONTGOMERY_NT,
    NEW_HEART,
    OPEN_ENGLISH,
    ETHERIDGE,
    REVISED_WEBSTER,
    REVISED_YOUNGS,
    KING_JAMES_UPDATED,
    WEBSTER,
    WESLEY_NT,
    WEYMOUTH_NT,
    TYNDALE,
    WORLD_ENGLISH,
    WYCLIFFE,
    YOUNGS,

    // Ancient Language Editions
    BIBLIA_HEBRAICA_STUTTGARTENSIA,
    LATIN_ERASMUS,
    GREEK_SEPTUAGINT,
    LATIN_VULGATE,
    MASORETIC_TEXT,
    NESTLE_ALAND,
    STEPHANUS_GNT,

    // Other English Translations
    AFRO,
    ALTERNATE_TRANSLATION,
    AMERICAN_SIGN_LANGUAGE,
    AMPLIFIED,
    ANALYTICAL_LITERAL,
    AUTHORIZED,
    JAMES_MOFFATT,
    BIKER,
    BRENTONS_ENGLISH_SEPTUAGINT,
    CHRISTIAN_COMMUNITY,
    COMMON,
    COMPLETE,
    COMPLETE_JEWISH,
    CONCORDANT,
    A_CONSERVATIVE_VERSION,
    CONTEMPORARY_ENGLISH,
    COTTON_PATCH,
    COVENANT,
    DAVID_ROBERT_PALMER,
    KING_JAMES_DEFINED,
    EASY_TO_READ,
    JUBILEE_2000,
    ENGLISH_MAJORITY_TEXT,
    ENGLISH_STANDARD,
    EXTREME,
    FERRAR_FENTON,
    GODS_LIVING_WORD,
    GODS_NEW_COVENANT,
    GODS_WORD,
    GOOD_NEWS,
    HOLMAN_CHRISTIAN_STANDARD,
    INTERNATIONAL_CHILDRENS,
    INTERNATIONAL_STANDARD_BIBLE,
    INTERNATIONAL_STANDARD_VERSION,
    JEWISH_NEW_TESTAMENT,
    JEWISH_OLD_TESTAMENT,
    KING_JAMES_2000,
    KING_JAMES_21,
    KING_JAMES_II,
    LEXHAM_ENGLISH,
    LITERAL,
    LIVING,
    MESSAGE,
    KING_JAMES_MODERN,
    MODERN_AMERICAN_ENGLISH_VERNACULAR,
    MODERN_LANGUAGE,
    NEW_AMERICAN,
    NEW_AMERICAN_STANDARD,
    NEW_CENTURY,
    NEW_ENGLISH_BIBLE,
    NEW_ENGLISH_TRANSLATION,
    NEW_EVANGELICAL,
    NEW_INTERNATIONAL_READERS,
    NEW_INTERNATIONAL,
    NEW_JERUSALEM,
    NEW_KING_JAMES,
    NEW_LIFE,
    NEW_LIVING,
    NEW_REVISED_STANDARD,
    NEW_SIMPLIFIED,
    J_B_PHILLIPS,
    CHARLES_B_WILLIAMS,
    WUEST,
    BARCLAY,
    NEW_WORLD,
    ORIGINAL_BIBLE_PROJECT,
    ORIGINAL_NEW_TESTAMENT,
    ORTHODOX_STUDY,
    POSTMODERN,
    RECOVERY,
    REVISED_AUTHORISED,
    REVISED_ENGLISH,
    KING_JAMES_REVISED,
    REVISED_STANDARD,
    REVISED,
    RIVERSIDE_NT,
    SCHOCKEN,
    SIMPLE_ENGLISH,
    THIRD_MILLENIUM,
    TODAYS_ENGLISH,
    TODAYS_NEW_INTERNATIONAL,
    UPDATED_BIBLE,
    VW_EDITION_2006,
    YES_WORD,
}

impl Version {
    pub fn code(self) -> &'static str {
        match self {
            // Open Source or Public Domain English Translations
            Version::AMERICAN_KING_JAMES => "AKJV",
            Version::AMERICAN_STANDARD => "ASV",
            Version::BIBLE_IN_BASIC_ENGLISH => "BBE",
            Version::WORLWIDE_ENGLISH => "BWE",
            Version::DARBY => "DAR",
            Version::DIAGLOT_NT => "Diaglot",
            Version::DOUAY_RHEIMS => "DR",
            Version::ROTHERHAM => "ROTH",
            Version::GENEVA => "GB",
            Version::KING_JAMES => "KJV",
            Version::LEESER => "LEESER",
            Version::LIVING_ORACLES_NT => "LONT",
            Version::KING_JAMES_MODERN_1963 => "MKJV1963",
            Version::MONTGOMERY_NT => "MONT",
            Version::NEW_HEART => "NHEB",
            Version::OPEN_ENGLISH => "OEB",
            Version::ETHERIDGE => "ETHERIDGE",
            Version::REVISED_WEBSTER => "RWEBSTER",
            Version::REVISED_YOUNGS => "RYLT",
            Version::KING_JAMES_UPDATED => "UKJV",
            Version::WEBSTER => "WBS",
            Version::WESLEY_NT => "WESLEY",
            Version::WEYMOUTH_NT => "WMTH",
            Version::TYNDALE => "TYN",
            Version::WORLD_ENGLISH => "WEB",
            Version::WYCLIFFE => "WYC",
            Version::YOUNGS => "YLT",

            // Ancient Language Editions
            Version::BIBLIA_HEBRAICA_STUTTGARTENSIA => "BHS",
            Version::LATIN_ERASMUS => "Erasmus",
            Version::GREEK_SEPTUAGINT => "LXX",
            Version::LATIN_VULGATE => "Vul",
            Version::MASORETIC_TEXT => "MT",
            Version::NESTLE_ALAND => "NA",
            Version::STEPHANUS_GNT => "Steph",

            // Other English Translations
            Version::AFRO => "ABT",
            Version::ALTERNATE_TRANSLATION => "ATB",
            Version::AMERICAN_SIGN_LANGUAGE => "ASL",
            Version::AMPLIFIED => "AB",
            Version::ANALYTICAL_LITERAL => "ALT",
            Version::AUTHORIZED => "AV",
            Version::JAMES_MOFFATT => "Mof",
            Version::BIKER => "BB",
            Version::BRENTONS_ENGLISH_SEPTUAGINT => "LXXE",
            Version::CHRISTIAN_COMMUNITY => "CCB",
            Version::COMMON => "COM",
            Version::COMPLETE => "AAT",
            Version::COMPLETE_JEWISH => "CJB",
            Version::CONCORDANT => "CONC",
            Version::A_CONSERVATIVE_VERSION => "ACV",
            Version::CONTEMPORARY_ENGLISH => "CEV",
            Version::COTTON_PATCH => "CPV",
            Version::COVENANT => "COV",
            Version::DAVID_ROBERT_PALMER => "DRP",
            Version::KING_JAMES_DEFINED => "DKJB",
            Version::EASY_TO_READ => "ERV",
            Version::JUBILEE_2000 => "JUBL2000",
            Version::ENGLISH_MAJORITY_TEXT => "EMTV",
            Version::ENGLISH_STANDARD => "ESV",
            Version::EXTREME => "ENT",
            Version::FERRAR_FENTON => "FF",
            Version::GODS_LIVING_WORD => "GLW",
            Version::GODS_NEW_COVENANT => "GNC",
            Version::GODS_WORD => "GW",
            Version::GOOD_NEWS => "GNB",
            Version::HOLMAN_CHRISTIAN_STANDARD => "HCSB",
            Version::INTERNATIONAL_CHILDRENS => "ICB",
            Version::INTERNATIONAL_STANDARD_BIBLE => "ISB",
            Version::INTERNATIONAL_STANDARD_VERSION => "ISV",
            Version::JEWISH_NEW_TESTAMENT => "JNT",
            Version::JEWISH_OLD_TESTAMENT => "JPS",
            Version::KING_JAMES_2000 => "KJ2000",
            Version::KING_JAMES_21 => "KJ21",
            Version::KING_JAMES_II => "KJII",
            Version::LEXHAM_ENGLISH => "LEB",
            Version::LITERAL => "LITV",
            Version::LIVING => "LB",
            Version::MESSAGE => "TM",
            Version::KING_JAMES_MODERN => "MKJV",
            Version::MODERN_AMERICAN_ENGLISH_VERNACULAR => "MAEV",
            Version::MODERN_LANGUAGE => "MLB",
            Version::NEW_AMERICAN => "NAB",
            Version::NEW_AMERICAN_STANDARD => "NASB",
            Version::NEW_CENTURY => "NCV",
            Version::NEW_ENGLISH_BIBLE => "NEB",
            Version::NEW_ENGLISH_TRANSLATION => "NET",
            Version::NEW_EVANGELICAL => "NEvT",
            Version::NEW_INTERNATIONAL_READERS => "NIrV",
            Version::NEW_INTERNATIONAL => "NIV",
            Version::NEW_JERUSALEM => "NJB",
            Version::NEW_KING_JAMES => "NKJV",
            Version::NEW_LIFE => "NLV",
            Version::NEW_LIVING => "NLT",
            Version::NEW_REVISED_STANDARD => "NRSV",
            Version::NEW_SIMPLIFIED => "NSB",
            Version::J_B_PHILLIPS => "JBP",
            Version::CHARLES_B_WILLIAMS => "Wms",
            Version::WUEST => "WUEST",
            Version::BARCLAY => "BAR",
            Version::NEW_WORLD => "NWT",
            Version::ORIGINAL_BIBLE_PROJECT => "OBP",
            Version::ORIGINAL_NEW_TESTAMENT => "ONT",
            Version::ORTHODOX_STUDY => "OSB",
            Version::POSTMODERN => "PMB",
            Version::RECOVERY => "REC",
            Version::REVISED_AUTHORISED => "RAV",
            Version::REVISED_ENGLISH => "REB",
            Version::KING_JAMES_REVISED => "RKJV",
            Version::REVISED_STANDARD => "RSV",
            Version::REVISED => "RV",
            Version::RIVERSIDE_NT => "RNT",
            Version::SCHOCKEN => "SCH",
            Version::SIMPLE_ENGLISH => "SEB",
            Version::THIRD_MILLENIUM => "TMB",
            Version::TODAYS_ENGLISH => "TEV",
            Version::TODAYS_NEW_INTERNATIONAL => "TNIV",
            Version::UPDATED_BIBLE => "UPDV",
            Version::VW_EDITION_2006 => "XXX",
            Version::YES_WORD => "YES",
        }
    }

    pub fn title(self) -> &'static str {
        match self {
            // Open Source or Public Domain English Translations
            Version::AMERICAN_KING_JAMES => "American King James Version",
            Version::AMERICAN_STANDARD => "American Standard Version",
            Version::BIBLE_IN_BASIC_ENGLISH => "Bible in Basic English",
            Version::WORLWIDE_ENGLISH => "Bible in WorldWide English NT",
            Version::DARBY => "Darby",
            Version::DIAGLOT_NT => "Diaglot NT - 1865",
            Version::DOUAY_RHEIMS => "Douay-Rheims",
            Version::ROTHERHAM => "The Emphasized Bible by J. B. Rotherham",
            Version::GENEVA => "Geneva Bible",
            Version::KING_JAMES => "King James Version",
            Version::LEESER => "Leeser Old Testament",
            Version::LIVING_ORACLES_NT => "Living Oracles NT",
            Version::KING_JAMES_MODERN_1963 => "Modern KJV 1963",
            Version::MONTGOMERY_NT => "Montgomery New Testament",
            Version::NEW_HEART => "New Heart English Bible",
            Version::OPEN_ENGLISH => "Open English Bible",
            Version::ETHERIDGE => "The Peschito Syriac New Testament",
            Version::REVISED_WEBSTER => "Revised 1833 Webster Version",
            Version::REVISED_YOUNGS => "Revised Young's Literal Translation NT",
            Version::KING_JAMES_UPDATED => "Updated King James Version",
            Version::WEBSTER => "Webster",
            Version::WESLEY_NT => "Wesley's New Testament",
            Version::WEYMOUTH_NT => "Weymouth NT",
            Version::TYNDALE => "Willam Tyndale Bible",
            Version::WORLD_ENGLISH => "World English Bible",
            Version::WYCLIFFE => "Wycliffe Bible",
            Version::YOUNGS => "Young's Literal Translation of the Bible",

            // Ancient Language Editions
            Version::BIBLIA_HEBRAICA_STUTTGARTENSIA => "Biblia Hebraica Stuttgartensia",
            Version::LATIN_ERASMUS => {
                "Erasmus Latin translation by Desiderius Erasmus Roterodamus"
            }
            Version::GREEK_SEPTUAGINT => "Greek Septuagint",
            Version::LATIN_VULGATE => "Latin Vulgate",
            Version::MASORETIC_TEXT => "Masoretic text",
            Version::NESTLE_ALAND => "Nestle-Aland Greek New Testament",
            Version::STEPHANUS_GNT => "Stephanus GNT",

            // Other English Translations
            Version::AFRO => "The Afro Bible Translation",
            Version::ALTERNATE_TRANSLATION => "The Alternate Translation Bible",
            Version::AMERICAN_SIGN_LANGUAGE => "American Sign Language Translation",
            Version::AMPLIFIED => "The Amplified Bible",
            Version::ANALYTICAL_LITERAL => "Analytical-Literal Translation",
            Version::AUTHORIZED => "Authorized Version",
            Version::JAMES_MOFFATT => "Bible: James Moffatt Translation",
            Version::BIKER => "The Biker Bible",
            Version::BRENTONS_ENGLISH_SEPTUAGINT => "Brenton's English Septuagint",
            Version::CHRISTIAN_COMMUNITY => "Christian Community Bible",
            Version::COMMON => "The Common Edition: New Testament",
            Version::COMPLETE => {
                "The Complete Bible: An American Translation, by Edgar Goodspeed and J. M. Powis Smith"
            }
            Version::COMPLETE_JEWISH => "Complete Jewish Bible",
            Version::CONCORDANT => "Concordant Version",
            Version::A_CONSERVATIVE_VERSION => "A Conservative Version",
            Version::CONTEMPORARY_ENGLISH => "Contemporary English Version",
            Version::COTTON_PATCH => "Cotton Patch Version, tr. Clarence Jordan",
            Version::COVENANT => "Covenant Edition New Testament",
            Version::DAVID_ROBERT_PALMER => "David Robert Palmer's translations of the gospels",
            Version::KING_JAMES_DEFINED => "Defined King James Version",
            Version::EASY_TO_READ => "Easy-to-Read Version",
            Version::JUBILEE_2000 => "English Jubilee 2000 Bible",
            Version::ENGLISH_MAJORITY_TEXT => "English Majority Text Version",
            Version::ENGLISH_STANDARD => "English Standard Version",
            Version::EXTREME => "Extreme New Testament",
            Version::FERRAR_FENTON => "Ferrar Fenton Bible",
            Version::GODS_LIVING_WORD => "God's Living Word",
            Version::GODS_NEW_COVENANT => {
                "God's New Covenant: A New Testament Translation, by Heinz W. Cassirer"
            }
            Version::GODS_WORD => "God's Word",
            Version::GOOD_NEWS => "Good News Bible",
            Version::HOLMAN_CHRISTIAN_STANDARD => "Holman Christian Standard Bible",
            Version::INTERNATIONAL_CHILDRENS => "International Children's Bible",
            Version::INTERNATIONAL_STANDARD_BIBLE => "International Standard Bible",
            Version::INTERNATIONAL_STANDARD_VERSION => "The International Standard Version",
            Version::JEWISH_NEW_TESTAMENT => {
                "Jewish New Testament: A Translation of the New Testament That Expresses Its Jewishness"
            }
            Version::JEWISH_OLD_TESTAMENT => "Jewish Publication Society AT",
            Version::KING_JAMES_2000 => "King James 2000",
            Version::KING_JAMES_21 => "King James for the 21st Century",
            Version::KING_JAMES_II => "King James Version II",
            Version::LEXHAM_ENGLISH => "The Lexham English Bible",
            Version::LITERAL => "The Literal Translation of the Holy Bible",
            Version::LIVING => "Living Bible",
            Version::MESSAGE => "The Message",
            Version::KING_JAMES_MODERN => "Modern King James Version",
            Version::MODERN_AMERICAN_ENGLISH_VERNACULAR => "Modern American English Vernacular",
            Version::MODERN_LANGUAGE => "Modern Language Bible: New Berkeley Version",
            Version::NEW_AMERICAN => "New American Bible",
            Version::NEW_AMERICAN_STANDARD => "New American Standard Bible",
            Version::NEW_CENTURY => "New Century Version",
            Version::NEW_ENGLISH_BIBLE => "New English Bible",
            Version::NEW_ENGLISH_TRANSLATION => "New English Translation",
            Version::NEW_EVANGELICAL => "New Evangelical Translation",
            Version::NEW_INTERNATIONAL_READERS => "New International Reader's Version",
            Version::NEW_INTERNATIONAL => "New International Version",
            Version::NEW_JERUSALEM => "New Jerusalem Bible",
            Version::NEW_KING_JAMES => "New King James Version",
            Version::NEW_LIFE => "New Life Version",
            Version::NEW_LIVING => "New Living Translation",
            Version::NEW_REVISED_STANDARD => "New Revised Standard Bible",
            Version::NEW_SIMPLIFIED => "New Simplified Bible",
            Version::J_B_PHILLIPS => "New Testament in Modern English, by J. B. Phillips",
            Version::CHARLES_B_WILLIAMS => "The New Testament in the Language of the People",
            Version::WUEST => "The New Testament (An Expanded Translation)",
            Version::BARCLAY => "The New Testament: A New Translation, by William Barclay",
            Version::NEW_WORLD => "New World Translation",
            Version::ORIGINAL_BIBLE_PROJECT => "The Original Bible Project",
            Version::ORIGINAL_NEW_TESTAMENT => {
                "The Original New Testament: The First Definitive Translation of the New Testament in 2000 Years, by Hugh Schonfield"
            }
            Version::ORTHODOX_STUDY => "Orthodox Study Bible",
            Version::POSTMODERN => "Postmodern Bible - Amos",
            Version::RECOVERY => "Recovery Version",
            Version::REVISED_AUTHORISED => "Revised Authorised Version",
            Version::REVISED_ENGLISH => "The Revised English Bible",
            Version::KING_JAMES_REVISED => "Revised King James New Testament",
            Version::REVISED_STANDARD => "The Revised Standard Version",
            Version::REVISED => "Revised Version",
            Version::RIVERSIDE_NT => "The Riverside New Testament",
            Version::SCHOCKEN => "The Schocken Bible",
            Version::SIMPLE_ENGLISH => "The Simple English Bible",
            Version::THIRD_MILLENIUM => "The Third Millenium Bible",
            Version::TODAYS_ENGLISH => "Today's English Version",
            Version::TODAYS_NEW_INTERNATIONAL => "Today's New International Version",
            Version::UPDATED_BIBLE => "Updated Bible Version",
            Version::VW_EDITION_2006 => "VW-Edition 2006",
            Version::YES_WORD => "Yes Word",
        }
    }
}

impl Default for Version {
    fn default() -> Self {
        Version::AMERICAN_STANDARD
    }
}

pub const DEFAULT_VERSION: Version = Version::AMERICAN_STANDARD;

#[cfg(test)]
mod tests {
    use super::Version;

    #[test]
    fn test_get_version_title() {
        assert_eq!(Version::KING_JAMES.title(), "King James Version");
    }
}