name: NOX Tests

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - main
      - develop
      - 'feature/**'

jobs:
  action-default-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          [
            ubuntu-20.04,
            ubuntu-22.04,
            windows-2019,
            windows-2022,
            macos-11,
            macos-12,
            macos-13,
          ]
    steps:
      - uses: actions/checkout@v3
      - uses: ./
      - run: nox --non-interactive --error-on-missing-interpreter --session tests
