name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          [
            ubuntu-20.04,
            ubuntu-22.04,
            windows-2019,
            windows-2022,
            macos-11,
            macos-12,
            macos-13,
          ]
    steps:
      - uses: actions/checkout@v3
      - uses: wntrblm/nox@2022.8.7
        with:
          python-versions: "3.8, 3.9, 3.10, 3.11, 3.12"
      - name: Test with NOX
        run: |
          nox --session tests
